---
# tasks file for apigee-opdk-setup-os-pg

- name: Update kernel.sem for postgres
  sysctl:
    name: kernel.sem
    value: '{{ apigee_kernel_sem }}'
    state: present
  tags:
  - sysctl

- name: Update limits.conf
  copy:
    src: apigee-pg.limits.conf
    dest: /etc/security/limits.d/apigee-pg.limits.conf
    owner: root
    group: root
    mode: 0644

