---
# tasks file for opdk-setup-os-pg

- name: Update kernel.sem for postgres
  lineinfile:
    dest: /etc/sysctl.conf
    line: 'kernel.sem = {{ apigee_kernel_sem }}'
    state: present
    backup: yes

- name: Update limits.conf
  copy:
    src: apigee-pg.limits.conf
    dest: /etc/security/limits.d/apigee-pg.limits.conf
    owner: root
    group: root
    mode: 0644
